---
- name: installing samba
  hosts: hosts
  vars_files:
    - paas.yaml          
  tasks:
        - name: installation of samba
          apt:
              name: samba
              state: latest
        - name: starting samba service
          service:
                  name: smbd
                  state: started
